name: PcComponentes Bronze Scraper

on:
  schedule:
    - cron: '40 9 * * 1'
  workflow_dispatch:

jobs:
  scraper-job:
    runs-on: ubuntu-latest
    
    # 🔥 ESTO ES LO QUE FALTABA: Forzar a que trabaje dentro de tu carpeta
    defaults:
      run:
        working-directory: aws_github

    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: 🚀 Ejecutar Scraper Ninja
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MY_S3_BUCKET: ${{ secrets.MY_S3_BUCKET }}
        run: python main.py
